// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vazaef.sazmanyar.Infrastructure.Persistance.Sql;

#nullable disable

namespace vazaef.sazmanyar.Infrastructure.Persistance.Sql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.ActionBudgetRequest.ActionBudgetRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BudgetAmountPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BudgetRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetRequestId");

                    b.ToTable("ActionBudgetRequestEntity");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.PlaceOfFinancing.FundingSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FundingSources");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.Request.RequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationYear")
                        .HasColumnType("int");

                    b.Property<long>("FundingSourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestingDepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FundingSourceId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequestingDepartmentId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.RequestType.RequestType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.RequestingUnit.RequestingDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestingDepartments");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.ActionBudgetRequest.ActionBudgetRequestEntity", b =>
                {
                    b.HasOne("vazaef.sazmanyar.Domain.Modles.Request.RequestEntity", "BudgetRequest")
                        .WithMany("ActionBudgetRequests")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetRequest");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.Request.RequestEntity", b =>
                {
                    b.HasOne("vazaef.sazmanyar.Domain.Modles.PlaceOfFinancing.FundingSource", "FundingSource")
                        .WithMany("Requests")
                        .HasForeignKey("FundingSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vazaef.sazmanyar.Domain.Modles.RequestType.RequestType", "RequestType")
                        .WithMany("Requests")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vazaef.sazmanyar.Domain.Modles.RequestingUnit.RequestingDepartment", "RequestingDepartment")
                        .WithMany("Requests")
                        .HasForeignKey("RequestingDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundingSource");

                    b.Navigation("RequestType");

                    b.Navigation("RequestingDepartment");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.PlaceOfFinancing.FundingSource", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.Request.RequestEntity", b =>
                {
                    b.Navigation("ActionBudgetRequests");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.RequestType.RequestType", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("vazaef.sazmanyar.Domain.Modles.RequestingUnit.RequestingDepartment", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
